const ImagesPath = {
  bg: require('../Assets/Images/bg2.png'), //my
  check2x: require('../Assets/Images/check3x.png'), //my
  logo: require('../Assets/Images/splash_logo.png'), //my
  background: require('../Assets/Images/app_bg.png'),
  white_back2: require('../Assets/Images/white_back2.png'),
  arabic: require('../Assets/Images/arabic.png'),
  us: require('../Assets/Images/us.png'),
  loginBg: require('../Assets/Images/Group_3350.png'),
  loginBg1: require('../Assets/Images/loginbg1.png'),
  loginBg2: require('../Assets/Images/loginbg2.png'),
  imagePlaceholder: require('../Assets/Images/Untitled-19.png'),
  drawerPlaceholder: require('../Assets/Images/drawerPlaceholder.png'),
  star: require('../Assets/Images/star.png'),
  homeDrawer: require('../Assets/Images/home.png'),
  earningDrawer: require('../Assets/Images/earning.png'),
  floatingCashDrawer: require('../Assets/Images/floatingCash.png'),
  taskDrawer: require('../Assets/Images/task.png'),
  deliveryDrawer: require('../Assets/Images/delivery.png'),
  historyDrawer: require('../Assets/Images/history.png'),
  helpDrawer: require('../Assets/Images/help.png'),
  logoutDrawer: require('../Assets/Images/logout.png'),
  otp: require('../Assets/Images/otp.png'),
  location: require('../Assets/Images/location.png'),
  rightarrow: require('../Assets/Images/rightarrow.png'),
  app_logo: require('../Assets/Images/logo.png'),
  menu: require('../Assets/Images/humburger3.png'),
  bell: require('../Assets/Images/notification3.png'),
  info: require('../Assets/Images/question_mark3.png'),
  homeDutyBanner: require('../Assets/Images/homeDutyBanner.png'),
  deliveryBoy: require('../Assets/Images/delivery2.png'),
  right: require('../Assets/Images/right.png'),
  foodPacket: require('../Assets/Images/foodPacket.png'),
  wallet: require('../Assets/Images/wallet.png'),
  arrow: require('../Assets/Images/arrow.png'),
  downArrow: require('../Assets/Images/downArrow.png'),
  backArrow: require('../Assets/Images/back3x.png'),
  locate: require('../Assets/Images/locate.png'),
  pickUpFood: require('../Assets/Images/pickUpFood.png'),
  pickUpInfo: require('../Assets/Images/pickUpInfo.png'),
  handMoney: require('../Assets/Images/handMoney.png'),
  camera: require('../Assets/Images/camera.png'),
  cameraSignup: require('../Assets/Images/camra2.png'),
  gallery: require('../Assets/Images/gallery.png'),
  profile: require('../Assets/Images/profile.png'),
};

export default ImagesPath;
