const ImagesPath = {
  bg: require('../Assets/Images/back1.png'), //my
  offer_setting: require('../Assets/Images/offer_setting.png'), //my
  check2x: require('../Assets/Images/check3x.png'), //my
  check: require('../Assets/Images/check.png'), //my
  logo: require('../Assets/Images/splash_logo.png'), //my
  background: require('../Assets/Images/app_bg.png'),
  veg: require('../Assets/Images/veg.png'),
  bug: require('../Assets/Images/bg3.png'),
  non_veg: require('../Assets/Images/non_veg.png'),
  checkmark: require('../Assets/Images/checkmark.png'),
  check1: require('../Assets/Images/check1.png'),
  uncheck: require('../Assets/Images/uncheck.png'),
  uncheck1: require('../Assets/Images/uncheck1.png'),
  white_back2: require('../Assets/Images/white_back2.png'),
  arabic: require('../Assets/Images/Image.png'),
  icici: require('../Assets/Images/icici.png'),
  refer: require('../Assets/Images/refer.png'),
  copy: require('../Assets/Images/copy.png'),
  right_new: require('../Assets/Images/right_new.png'),
  us: require('../Assets/Images/uk1.png'),
  loginBg: require('../Assets/Images/Group_3350.jpg'),
  loginBg1: require('../Assets/Images/Slide1.png'),
  loginBg2: require('../Assets/Images/slide2.png'),
  imagePlaceholder: require('../Assets/Images/Untitled-19.png'),
  drawerPlaceholder: require('../Assets/Images/drawerPlaceholder.png'),
  star: require('../Assets/Images/star.png'),
  reset: require('../Assets/Images/reset.png'),
  homeDrawer: require('../Assets/Images/home.png'),
  up: require('../Assets/Images/up.png'),
  filter: require('../Assets/Images/filter.png'),
  earningDrawer: require('../Assets/Images/earning.png'),
  floatingCashDrawer: require('../Assets/Images/floatingCash.png'),
  taskDrawer: require('../Assets/Images/task.png'),
  deliveryDrawer: require('../Assets/Images/delivery.png'),
  historyDrawer: require('../Assets/Images/history.png'),
  helpDrawer: require('../Assets/Images/help.png'),
  logoutDrawer: require('../Assets/Images/logout.png'),
  otp: require('../Assets/Images/otp1.png'),
  hungry: require('../Assets/Images/hungry.png'),
  user: require('../Assets/Images/user.png'),
  search: require('../Assets/Images/search.png'),
  card: require('../Assets/Images/card.png'),
  location: require('../Assets/Images/location.png'),
  coupon: require('../Assets/Images/coupon.png'),
  notification: require('../Assets/Images/notification.png'),
  rightarrow: require('../Assets/Images/rightarrow.png'),
  app_logo: require('../Assets/Images/logo.png'),
  menu: require('../Assets/Images/humburger3.png'),
  bell: require('../Assets/Images/notification3.png'),
  info: require('../Assets/Images/question_mark3.png'),
  homeDutyBanner: require('../Assets/Images/homeDutyBanner.png'),
  deliveryBoy: require('../Assets/Images/delivery2.png'),
  right: require('../Assets/Images/right.png'),
  foodPacket: require('../Assets/Images/foodPacket.png'),
  wallet: require('../Assets/Images/wallet.png'),
  arrow: require('../Assets/Images/arrow.png'),
  downArrow: require('../Assets/Images/downArrow.png'),
  backArrow: require('../Assets/Images/back3x.png'),
  locate: require('../Assets/Images/locate.png'),
  pickUpFood: require('../Assets/Images/pickUpFood.png'),
  pickUpInfo: require('../Assets/Images/pickUpInfo.png'),
  handMoney: require('../Assets/Images/handMoney.png'),
  camera: require('../Assets/Images/camera.png'),
  cameraSignup: require('../Assets/Images/camra2.png'),
  gallery: require('../Assets/Images/gallery.png'),
  profile: require('../Assets/Images/profile.png'),
  whatsapp: require('../Assets/Images/whatsapp.png'),
  gmail: require('../Assets/Images/gmail.png'),
  fb: require('../Assets/Images/fb.png'),
  Insta: require('../Assets/Images/Insta.png'),
  Sms: require('../Assets/Images/Sms.png'),
  phonecall: require('../Assets/Images/phonecall.png'),
  locActive: require('../Assets/Images/location-active.png'),
  userActive: require('../Assets/Images/user-active.png'),
  cartActive: require('../Assets/Images/cart-active.png'),
  searchActive: require('../Assets/Images/search-active.png'),
};
 


export default ImagesPath
