// Libraries
import React from 'react';
import { StyleSheet, I18nManager } from 'react-native';

// Assets
// assets
import {
  screenWidth,
  screenHeight,
  ImagesPath,
  Colors,
  Fonts,
  Scale,
} from '../../CommonConfig';

export const AuthStyle = StyleSheet.create({
  imageBg: {
    flex: 1,
    resizeMode: 'cover',
  },
  languageCont: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  languateHeaderText: {
    fontSize: Scale(35),
    color: Colors.BLACK,
    fontFamily: Fonts.Bold,
    fontWeight:'bold',
    marginLeft: Scale(40),
  },
  languateHeaderText2: {
    fontSize: Scale(35),
    color: Colors.APPCOLOR,
    fontFamily: Fonts.Bold,
    marginLeft: Scale(30),
  },
  languageTouchable: {
    flexDirection: 'row',
    width: '80%',
    paddingLeft: Scale(5),
    paddingRight: Scale(10),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: Scale(46),
    marginTop: Scale(20),
  },
  languageText: {
    fontSize: Scale(18),
    marginLeft:Scale(6),
    color: Colors.BLACK,
    fontFamily: Fonts.Medium,
    paddingHorizontal: Scale(10),
  },
  buttonText: {
    fontWeight:'bold',
    fontSize: Scale(16),
    color: Colors.WHITE,
    fontFamily: Fonts.Medium,
  },
  loginTouchable: {
    borderRadius: Scale(20),
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: Scale(45),
    backgroundColor: Colors.BUTTON_COLOR,
    marginTop: Scale(30),
  },
  keyboardAware: {
    flex: 1,
    backgroundColor: Colors.THEME_COLOR,
  },
  loginBg: {
    width: screenWidth,
    height: screenHeight,
  },
  loginInputCont: {
    top: Scale(-30),
    paddingTop: Scale(10),
    borderTopLeftRadius: Scale(30),
    borderTopRightRadius: Scale(30),
    backgroundColor: Colors.WHITE,
  },
  mobileNumberText: {
    color: Colors.BLACK,
    opacity: 0.53,
    textAlign: 'left',
    width: '80%',
    alignSelf: 'center',
    fontSize: Scale(14),
    fontFamily: Fonts.Medium,
    borderColor: '#707070',
  },
  loginTextInput: {
    color: Colors.BLACK,
    height: Scale(45),
    borderWidth: 1,
    borderColor: Colors.BORDERCOLOR,
    width: '80%',
    alignSelf: 'center',
    fontSize: Scale(16),
    marginTop: Scale(5),
    padding: Scale(10),
borderRadius:Scale(5),
    fontFamily: Fonts.Light,
  },
  mobileNumberText2: {
    color: Colors.BLACK,
    opacity: 0.53,
    textAlign: 'left',
    width: '90%',
    alignSelf: 'center',
    fontSize: Scale(14),
    fontFamily: Fonts.Light,
    borderColor: '#707070',
  },
  loginTextInput2: {
    color: Colors.BLACK,
    height: Scale(45),
    borderWidth: 1,
    borderColor: Colors.BORDERCOLOR,
    width: '90%',
    alignSelf: 'center',
    fontSize: Scale(16),
    marginTop: Scale(5),
    padding: Scale(5),
    paddingLeft:Scale(8),
    borderRadius: Scale(5),
    fontFamily: Fonts.Light,
  },
  signUpText: {
    alignSelf: 'center',
    fontSize: Scale(14),
    fontFamily: Fonts.Medium,
    marginTop: Scale(30),
    textAlign: 'center',
  },
  resendOTP: {
    alignSelf: 'center',
    fontSize: Scale(16),
    fontFamily: Fonts.Medium,
    marginTop: Scale(15),
    textAlign: 'center',
    width: '80%',
    color: Colors.WHITE,
    textDecorationLine: 'underline'
  },
  OTPDesc: {
    color: Colors.WHITE,
    width: '80%',
    alignSelf: 'center',
    fontSize: Scale(14),
    fontFamily: Fonts.Medium,
    lineHeight: 28,
  },
  backArrowCont: {
    height: '20%',
    alignItems: 'center',
    paddingHorizontal: Scale(20),
    flexDirection: 'row',
  },
  signUpHeaderText: {
    color: Colors.WHITE,
    marginLeft: Scale(15),
    fontSize: Scale(16),
    fontFamily: Fonts.Medium,
  },
  uploadDocText: {
    marginTop: Scale(20),
    textAlign: 'left',
    fontSize: Scale(16),
    color: Colors.BLACK,
    fontFamily: Fonts.Medium,
  },
  imageText: {
    fontFamily: Fonts.Medium,
    color: Colors.BLACK,
    fontSize: Scale(14),
  },
  uploadButtonText: {
    fontSize: Scale(14),
    color: Colors.LIGHT_GRAY,
    fontFamily: Fonts.Medium,
  },
  uploadTouchable: {
    paddingHorizontal: Scale(15),
    paddingVertical: Scale(8),
    backgroundColor: Colors.DOCUPLOAD,
    borderRadius: Scale(5),
  },
  docSelectText: {
    marginLeft: Scale(20),
    fontSize: Scale(16),
    fontFamily: Fonts.Medium,
  },
  modalDocTouchable: {
    flexDirection: 'row',
    height: Scale(45),
    width: '90%',
    alignSelf: 'center',
    alignItems: 'center',
    borderWidth: 1,
    paddingLeft: Scale(10),
    borderRadius: Scale(10),
  },
  modalBg: {
    backgroundColor: 'rgba(0,0,0,0.4)',
    height: '100%',
    width: '100%',
    justifyContent: 'flex-end',
  },
  modalCont: {
    height: '100%',
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: Scale(20),
    borderTopRightRadius: Scale(20),
  },
  modalDynami: {
    backgroundColor: Colors.WHITE,
    borderTopLeftRadius: Scale(20),
    borderTopRightRadius: Scale(20),
    minHeight: '40%',
    justifyContent: 'center',
  },
  modalItemCont: {
    backgroundColor: 'rgba(200,200,200,0.4)',
    width: '95%',
    alignSelf: 'center',
    borderRadius: Scale(20),
    alignItems: 'center',
    // borderColor: Color.ThemeColor
  },
  modalText: {
    paddingVertical: Scale(10),
    // color: Color.placeHolderColor,
    fontFamily: Fonts.Regular,
    fontSize: Scale(15),
  },
});
