export const APPLY_COUPON = 'APPLY_COUPON'

export const SET_APPLY_COUPON_LOADER = 'SET_APPLY_COUPON_LOADER'

export const SET_APPLY_COUPON_ERROR = 'SET_APPLY_COUPON_ERROR'

export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS'

export const SET_COUPON_CODE = 'SET_COUPON_CODE'

export const REMOVE_COUPON = 'REMOVE_COUPON'
