export const ADD_TO_CART = 'ADD_TO_CART'

export const SUB_TO_CART = 'SUB_TO_CART'

export const SET_INSTRUCTION = 'SET_INSTRUCTION'

export const SET_ADDRESS_ID = 'SET_ADDRESS_ID'

export const SET_SELECTED_ADDRESS = 'SET_SELECTED_ADDRESS'

export const CREATE_ORDER = 'CREATE_ORDER'

export const SET_CREATE_ORDER_LOADER = 'SET_CREATE_ORDER_LOADER'

export const SET_CREATE_ORDER_ERROR = 'SET_CREATE_ORDER_ERROR'

export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
