export const ORDER_LIST = 'ORDER_LIST'

export const SET_ORDER_LIST_LOADER = 'SET_ORDER_LIST_LOADER'

export const SET_ORDER_LIST_ERROR = 'SET_ORDER_LIST_ERROR'

export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
