// =======>>   LOADER ACTIONS <<<<<<<=======
export const LOADER_REQUEST = 'LOADER_REQUEST'

// =======>>   LOGIN ACTIONS <<<<<<<=======
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const DESTROY_SESSION = 'DESTROY_SESSION'
export const SET_INTRO_COMPLETE = 'SET_INTRO_COMPLETE'

// =======>>   SIGN-UP ACTIONS <<<<<<<=======
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCES'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'
export const SET_SIGNUP_STATUS = 'SET_SIGNUP_STATUS'
export const SIGNUP_LOGIN = 'SIGNUP_LOGIN'
export const MAKE_SIGNUP_SUCCESS = 'MAKE_SIGNUP_SUCCESS'

// =======>>   OTP-UP ACTIONS <<<<<<<=======
export const OTP_REQUEST = 'OTP_REQUEST'
export const OTP_SUCCESS = 'OTP_SUCCESS'
export const OTP_FAILED = 'OTP_FAILED'

// =======>>   OTP-UP ACTIONS <<<<<<<=======
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST'
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS'
export const OTP_VERIFY_FAILED = 'OTP_VERIFY_FAILED'

// =======>>   ABOUT-US ACTIONS <<<<<<<=======
export const ABOUTUS_REQUEST = 'ABOUTUS_REQUEST'
export const ABOUTUS_SUCCESS = 'ABOUTUS_SUCCESS'
export const ABOUTUS_FAILED = 'ABOUTUS_FAILED'

// =======>>   PRIVACY ACTIONS <<<<<<<=======
export const PRIVACY_REQUEST = 'PRIVACY_REQUEST'
export const PRIVACY_SUCCESS = 'PRIVACY_SUCCESS'
export const PRIVACY_FAILED = 'PRIVACY_FAILED'

// =======>>   TERMS AND CONDITIONS ACTIONS <<<<<<<=======
export const TERMS_REQUEST = 'TERMS_REQUEST'
export const TERMS_SUCCESS = 'TERMS_SUCCESS'
export const TERMS_FAILED = 'TERMS_FAILED'

// =======>>   FAQ ACTIONS <<<<<<<=======
export const FAQ_REQUEST = 'FAQ_REQUEST'
export const FAQ_SUCCESS = 'FAQ_SUCCESS'
export const FAQ_FAILED = 'FAQ_FAILED'

// =======>>   HELP AND SUPPORT ACTIONS <<<<<<<=======
export const HELP_REQUEST = 'HELP_REQUEST'
export const HELP_SUCCESS = 'HELP_SUCCESS'
export const HELP_FAILED = 'HELP_FAILED'

// =======>>   ADD ADDRESS ACTIONS <<<<<<<=======
export const ADDADDRESS_REQUEST = 'ADDADDRESS_REQUEST'
export const ADDADDRESS_SUCCESS = 'ADDADDRESS_SUCCESS'
export const ADDADDRESS_FAILED = 'ADDADDRESS_FAILED'

// =======>>   ADDRESS LIST ACTIONS <<<<<<<=======
export const ADDRESSLIST_REQUEST = 'ADDRESSLIST_REQUEST'
export const ADDRESSLIST_SUCCESS = 'ADDRESSLIST_SUCCESS'
export const ADDRESSLIST_FAILED = 'ADDRESSLIST_FAILED'
export const SET_ADDRESS_LIST_LOADER = 'SET_ADDRESS_LIST_LOADER'

// =======>>   DELETE ADDRESS ACTIONS <<<<<<<=======
export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST'
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_FAILED = 'DELETE_ADDRESS_FAILED'

// =======>>  CHANGE ORDER STATUS ACTIONS <<<<<<<=======
export const CHANGE_ORDER_STATUS_REQUEST = 'CHANGE_ORDER_STATUS_REQUEST'
export const CHANGE_ORDER_STATUS_LOADER = 'CHANGE_ORDER_STATUS_LOADER'
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS'
export const CHANGE_ORDER_STATUS_FAILED = 'CHANGE_ORDER_STATUS_SUCCESS'

// =======>>   OFFER CARD ACTIONS <<<<<<<=======
export const OFFER_CARD_REQUEST = 'OFFER_CARD_REQUEST'
export const OFFER_CARD_SUCCESS = 'OFFER_CARD_SUCCESS'
export const OFFER_CARD_FAILED = 'OFFER_CARD_FAILED'

// =======>>   COUPON  ACTIONS <<<<<<<=======
export const COUPON_REQUEST = 'COUPON_REQUEST'
export const COUPON_SUCCESS = 'COUPON_SUCCESS'
export const COUPON_FAILED = 'COUPON_FAILED'

// =======>>   SEARCH ACTIONS <<<<<<<=======
export const SEARCH_REQUEST = 'SEARCH_REQUEST'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILED = 'SEARCH_FAILED'

// =======>>  MY ORDER LIST ACTIONS <<<<<<<=======
export const MYORDER_LIST_REQUEST = 'MYORDER_LIST_REQUEST'
export const MYORDER_LIST_SUCCESS = 'MYORDER_LIST_SUCCESS'
export const MYORDER_LIST_FAILED = 'MYORDER_LIST_FAILED'

// =======>>   EDIT PROFILE ACTIONS <<<<<<<=======
export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const SET_EDIT_PROFILE_LOADER = 'SET_EDIT_PROFILE_LOADER'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED'
export const SET_EDIT_PROFILE_STATUS = 'SET_EDIT_PROFILE_STATUS'

// =======>>  ADD FAVOURITE ACTIONS <<<<<<<=======
export const ADD_FAVOURITE_REQUEST = 'ADD_FAVOURITE_REQUEST'
export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS'
export const ADD_FAVOURITE_FAILED = 'ADD_FAVOURITE_FAILED'
export const SET_FAVOURITE_LOADER = 'SET_FAVOURITE_LOADER'

// =======>>  FAVOURITE LIST ACTIONS <<<<<<<=======

export const FAVOURITE_LIST_REQUEST = 'FAVOURITE_LIST_REQUEST'
export const FAVOURITE_LIST_SUCCESS = 'FAVOURITE_LIST_SUCCESS'
export const FAVOURITE_LIST_FAILED = 'FAVOURITE_LIST_FAILED'
export const SET_FAVOURITE_LIST_LOADER = 'SET_FAVOURITE_LIST_LOADER'

// =======>>   OTP-UP ACTIONS <<<<<<<=======
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

// =======>>  CHANGE PASSWORD ACTIONS <<<<<<<=======

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'

// =======>>  CHANGE PASSWORD ACTIONS <<<<<<<=======

export const HUNGRY_NOW_LIST_REQUEST = 'HUNGRY_NOW_LIST_REQUEST'
export const HUNGRY_NOW_LIST_SUCCESS = 'HUNGRY_NOW_LIST_SUCCESS'
export const HUNGRY_NOW_LIST_FAILED = 'HUNGRY_NOW_LIST_FAILED'
export const SET_HUNGRY_NOW_LIST_LOADER = 'SET_HUNGRY_NOW_LIST_LOADER'

// =======>>  HUNGRY NOW LIST ACTIONS <<<<<<<=======

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAILED = 'ORDER_DETAILS_FAILED'

// =======>>  COUNTRY CODE LIST ACTIONS <<<<<<<=======

export const COUNTRY_LIST_REQUEST = 'COUNTRY_LIST_REQUEST'
export const COUNTRY_LIST_SUCCESS = 'COUNTRY_LIST_SUCCESS'
export const COUNTRY_LIST_FAILED = 'COUNTRY_LIST_FAILED'

// =======>>  OFFER LIST ACTIONS <<<<<<<=======

export const OFFER_LIST_REQUEST = 'OFFER_LIST_REQUEST'
export const OFFER_LIST_SUCCESS = 'OFFER_LIST_SUCCESS'
export const OFFER_LIST_FAILED = 'OFFER_LIST_FAILED'
export const OFFER_LIST_LOADER = 'OFFER_LIST_LOADER'

// =======>>   GET USER DETAILS ACTIONS <<<<<<<=======
export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST'
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAILED = 'GET_USER_DETAILS_FAILED'
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS'
export const SET_USER_DETAILS = 'SET_USER_DETAILS'



export const SET_OTP_VERIFY_STATUS = 'SET_OTP_VERIFY_STATUS'
